<?php
$title = 'Commissions';
include('include/header.php');
?>
<!-- title -->
<div class="title">
    <div class="container">
        <div class="row py-5">
            <div class="col py-4">
                <h1><?php echo $title; ?></h1>
            </div>
        </div>
    </div>
</div>
<!-- title -->
<!-- content -->
<div class="content">
    <div class="container">
        <div class="row py-5">
            <div class="col">
                <h2 class="mb-3">Scientific Program Overview 2020</h2>
                <p>As a preview to the interesting discussions which will be held in Sydney, listed below are the titles/topics of scientific event proposals generated by Commissions and Panels from suggestions submitted by Associates. The list below is preliminary.
                    Furthermore, the preliminary program will be modified by the Program Committee when it meets in March 2019, to a greater or lesser degree, in order to minimize overlap, maximize inter-commission co-ordination, and respond to imperatives set down by
                    the Bureau and COSPAR Scientific Advisory Committee concerning the general organization of the Assembly. Events organized jointly by two Commissions are listed only once, so it is necessary to scan the entire list for a proper overview of the
                    forthcoming Assembly scientific program.</p>
                <div class="commissions">
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>A</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Space Studies of the Earth's Surface, Meteorology and Climate
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/a.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>The Interface Between Spacecraft Instrument Technologies and the Science They Enable</li>
                                <li>GEO</li>
                                <li>Observing the Anthropocene from Space</li>
                                <li>Land-Ocean-Atmosphere Interactions</li>
                                <li>CubeSats for Scientific and Civil-use Studies of the Earth</li>
                                <li>Space-based and Sub-orbital Observations of Atmospheric Physics and Chemistry</li>
                                <li>Science and Applications Enabled by Oceanographic Satellite Measurements</li>
                                <li>Advances in Quantitative Remote Sensing and Application for Global Terrestrial Ecosystems</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>B</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Space Studies of the Earth-Moon System, Planets, and Small Bodies of the Solar System
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/b.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>Unifying Planetary System Formation out of Elementary Building Blocks: from Dust, Gas and Ice to our Solar System and Exoplanets</li>
                                <li>Human and Robotic Exploration of Moon, Mars, and Asteroids</li>
                                <li>Lunar, Mars, and Asteroid Resources</li>
                                <li>Technologies for Planetary Research</li>
                                <li>Planetary Cubesats and Small Sats</li>
                                <li>Planetary Instruments</li>
                                <li>Small Body Exploration Science in the New Decade</li>
                                <li>Planetary Exploration, Horizon 2061: Report to COSPAR and Discussion</li>
                                <li>Asteroids, Friends Or Foe: Planetary Defense and Resources</li>
                                <li>Results from the Exploration of the Kuiper Belt by NASA’s New Horizons Mission</li>
                                <li>Reference Frames</li>
                                <li>Lunar Science and Exploration</li>
                                <li>Science Enabled by a Lunar Outpost</li>
                                <li>Mars Science Results</li>
                                <li>Forward Planning for the Robotic Exploration of Mars</li>
                                <li>Mars Sample Return</li>
                                <li>Venus Science and Exploration</li>
                                <li>Mercury: New Results and Future Exploration</li>
                                <li>Juno at Jupiter</li>
                                <li>Gas Giant Planet Systems</li>
                                <li>Ocean Worlds</li>
                                <li>Ice Giant Systems</li>
                                <li>Current and Future Projects for Exoplanet Detections and Characterization</li>
                                <li>The Study of Exoplanet Atmospheres and the Search for Life Outside of the Solar System</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>C</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Space Studies of the Upper Atmospheres of the Earth and Planets Including Reference Atmospheres
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/c.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>International Standards on Space Environment from ISO</li>
                                <li>Advances in Remote Sensing of the Middle and Upper Atmosphere and Ionosphere from the Ground and from Space, including Sounding Rockets and Multi-Instrument Studies</li>
                                <li>Variabilities of Radio Wave Propagation Characteristics in Lower Ionosphere</li>
                                <li>Recent Advances in Equatorial, Low- and Mid-Latitude Mesosphere, Thermosphere and Ionosphere Studies</li>
                                <li>The Coupled Solar Wind-Magnetosphere-Ionosphere-Thermosphere System and the Impact of Solar and Geomagnetic Storms on Geospace</li>
                                <li>Conditions for Enhanced Risk in Ionospheric Weather</li>
                                <li>CSES and Swarm Data Analysis of the Ionosphere Dynamics at Different Temporal and Spatial Scales</li>
                                <li>The Physics and Dynamics of the Middle Atmosphere from Mid to High Latitudes</li>
                                <li>Wave Coupling Processes and Consequences in the Whole Atmosphere and Ionosphere</li>
                                <li>Advances in External Forcing Studies for the Middle Atmosphere and Lower Ionosphere</li>
                                <li>Small Satellite Missions for Aeronomy and Ionosphere Studies</li>
                                <li>Planetary Atmospheres</li>
                                <li>Planetary Upper Atmospheres, Ionospheres and Magnetospheres</li>
                                <li>Imaging the Planets in X-rays</li>
                                <li>Improving the Description of Hemispheric Differences in Ionospheric Models</li>
                                <li>Development of Models Related to the COSPAR International Reference Atmosphere and to ISO Standards for the Atmosphere</li>
                                <li>Venus International Reference Atmosphere, VIRA Update</li>
                                <li>Active Space Experiments</li>
                                <li>Dust Detection and Observation in Space and Laboratory Experiments</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>D</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Space Plasmas in the Solar System, Including Planetary Magnetospheres
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/d.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>Overview Talks</li>
                                <li>GCR</li>
                                <li>Large Scale Heliosphere</li>
                                <li>Pickup Ions in the Heliosphere and Beyond</li>
                                <li>Propagation of Solar Energetic Particles in the Heliosphere</li>
                                <li>Space Climate</li>
                                <li>Solar Probe and SolO</li>
                                <li>Thermal and Dynamic Plasma Instabilities on Multiscales: From Laboratories to Planets, the Sun/Stars, Galaxies, and Beyond</li>
                                <li>Sun-Heliosphere Connection Events: Origin, Propagation, Impact and Prediction</li>
                                <li>Nonthermal Particles in the Inner Heliosphere: Origin and Consequences</li>
                                <li>Highlights of Magnetospheric Plasma Physics</li>
                                <li>Cross-scale Coupling and Multi-point Observations in the Magnetosphere</li>
                                <li>Non-thermal Distributions in Space Plasmas and their Role in Wave Generation, and Heating and Acceleration of Particles</li>
                                <li>Plasma Transport across Magnetospheric Boundaries</li>
                                <li>Particle Acceleration and Loss in the Earth and Planetary Magnetospheres</li>
                                <li>Magnetotail Dynamics and Substorms during Storm and Non-storm Time</li>
                                <li>Imaging of the Magnetosphere</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>E</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Research in Astrophysics from Space
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/e.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>Fast Spinning Neutron Stars</li>
                                <li>Accretion and Ejection in Galactic Compact ObjectsThe Gravitational Wave Universe in the LIGO-Virgo Era</li>
                                <li>LISA, the Next Window on the Universe</li>
                                <li>High-energy Processes at the Galactic Center</li>
                                <li>Long-term All-sky Monitoring of High Energy Transient Sources</li>
                                <li>Cherenkov Telescope Array: the Ground-based Eyes to Observe the Gamma-ray Universe</li>
                                <li>Origin of Cosmic Rays</li>
                                <li>The Space View of Radio Galaxies</li>
                                <li>Probing Energy Extraction from Supermassive Black Holes</li>
                                <li>Early Results of Spectrum-Roentgen-Gamma Mission</li>
                                <li>The Remnants of Supernova Explosions</li>
                                <li>Astronomy from Space and the Ground: Synergies and Challenges</li>
                                <li>Black Hole Astrophysics: Observational Evidence and Theoretical Models</li>
                                <li>Accretion on All Scales</li>
                                <li>X- and Gamma-ray Counterparts of New Transients in the Multimessenger Era</li>
                                <li>Observations and Prospects for X-ray Polarimetry</li>
                                <li>Evolution of Disk and Corona in X-ray Binaries: Intersection of Observations and Modeling</li>
                                <li>Multi Wavelength Studies of Compact Objects - into the 21st Century</li>
                                <li>Magnetic Flux Ropes in Solar and Stellar Environments</li>
                                <li>Magnetic Structures of Solar Filaments</li>
                                <li>Driving Solar Eruptions</li>
                                <li>New Views on the Solar Magnetic Atmosphere</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>F</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Life Sciences as Related to Space
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/f.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>Gravity Perception and Response in Plants and Fungi: Ground and Space Studies</li>
                                <li>Biological Effects of Space Radiation: a Controllable Challenge for Long-term Human Space Missions</li>
                                <li>Space Radiation Risk, Quality of Radiation and Countermeasures: Physical and Biophysical Mechanisms, Modelling and Simulations</li>
                                <li>Space Radiation: Dosimetric Measurements and Related Models, Radiation Detector Developments and their Ground-Based Characterization</li>
                                <li>Genetic, Epigenetic and Metabolic Changes in Spaceflight and Simulated Spaceflight Environment</li>
                                <li>Simulating the Deep Space Radiation Environment on a Journey to Mars-The NASA Galactic Cosmic Ray Simulator Project and Approaches to Risk Modelling and Mitigation</li>
                                <li>Chemical Evolution and Origin of Life</li>
                                <li>Astrobiology: Laboratory Experiments, Field Studies in Analogue Environments and Space Experiments in Low Earth Orbit</li>
                                <li>Habitability in the Solar System and Beyond</li>
                                <li>Biosignatures and Biomarkers--Searching for Traces of Prebiotic Organic Compounds or Forms of Past or Present Life in the Solar System</li>
                                <li>Pre-biotic and Complex Molecules in the Universe: Observational, Laboratory, and Computational Perspectives on the Evolution of Molecular Complexity</li>
                                <li>Climate and Astrobiological Potential of Icy Deposits on Mars</li>
                                <li>Bioregenerative Life Support – Past–Present–Future / Outlook and Ecological Aspects</li>
                                <li>Advanced Life Support Test Beds and Facilities</li>
                                <li>Influence of Spaceflight Environments on Biological Systems</li>
                                <li>Modelling and Control to Support Closure of Manmade Ecosystems and Biospheres</li>
                                <li>Space Food and Nutrition</li>
                                <li>Molecular, Cellular and Physiological Changes in Response to Spaceflight and Ground-based Analogues</li>
                                <li>"There and Back Again - An Astronaut’s Tale: NASA ""Red"" Risks to Human Health and Performance for a Martian Journey"</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>G</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Materials Sciences in Space
                        </div>
                        <div class="col-4 col-md-2">
                            <img src="img/commissions/g.jpg" class="img-fluid w-100" alt="">
                        </div>
                        <div class="col-md">
                            <ul>
                                <li>Gravitational Effects on Physico-Chemical Processes</li>
                                <li>Drop Tower Days</li>
                                <li>Influence of Free Space Environment on the Behaviour of Materials</li>
                            </ul>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-2 col-md-1">
                            <h2>H</h2>
                        </div>
                        <div class="col col-md-2 name">
                            Fundamental Physics in Space
                        </div>
                        <div class="col-4 col-md-2"></div>
                        <div class="col-md">
                            <ul>
                                <li>Commission H Highlight Talks</li>
                                <li>Gravitation, Dark Energy and Dark Matter</li>
                                <li>Space Missions for Fundamental Physics</li>
                                <li>Gravitational Wave Astrophysics</li>
                                <li>Applications (Geodesy, Metrology, Navigation, and Others)</li>
                                <li>Enabling Technologies for Fundamental Physics Experiments and Missions</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <h2 class="mt-5 mb-3">Panels and Special Events</h2>
                <div class="row">
                    <div class="col-md-6">
                        <ul>
                            <li>Latest Results</li>
                            <li>Small Satellites for Capacity Building</li>
                            <li>Teacher Training Workshop</li>
                            <li>Current Trends, Initiatives and Research in Education and Outreach for Space Sciences</li>
                            <li>Space Debris: Scientific Foundation Enabling Long-Term Sustainability</li>
                            <li>Establishing a Framework for Environmental Stewardship on Celestial Bodies</li>
                            <li>A Shared Scientific Vision for Global Space Exploration</li>
                            <li>Missions and Data Sets for Radiation Belt Modelling</li>
                            <li>Development of Global Physical, Empirical, and Data Assimilative Models of the Radiation Belt Environment</li>
                            <li>Dedicated Tools for Radiation Belt Modelling and Data Processing: An Opportunity to Gather Efforts</li>
                            <li>Scientific Ballooning: Recent Developments in Technology and Instrumentation</li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        <ul>

                            <li>Satellite Dynamics - new Developments and Challenges for Earth and Solar System Sciences</li>
                            <li>Space Weather Capabilities Assessment</li>
                            <li>Space Weather Information Architecture and Its Roles in Enhancing Data Access and Utilization</li>
                            <li>Global Coordination in Space Weather. Interfacing with User Groups</li>
                            <li>Roadmap Update and Topical Action Teams Progress</li>
                            <li>Planetary and Interplanetary Space Weather</li>
                            <li>Nowcast and Forecast on Ionospheric Indices and Related Scales for Space Weather Services</li>
                            <li>Hands-on Education in Space Weather</li>
                            <li>You are COSPAR!</li>
                            <li>Deep Space Science Enabled by Daughter Nanosats</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content -->
<?php
            include('include/footer.php');
            ?>
